# Generated by Django 5.1 on 2024-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='filmes/fotos')),
                ('categoria', models.CharField(choices=[('acao', 'Ação'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('ficcao', 'Ficção Científica'), ('romance', 'Romance')], max_length=20)),
            ],
        ),
    ]
